(* ========================================================================= *)
(* HOL-Light Library for Modal Systems                                       *)
(*                                                                           *)
(* (c) Copyright, Marco Maggesi, Cosimo Perini Brogi 2020-2022.              *)
(* (c) Copyright, Antonella Bilotta, Marco Maggesi,                          *)
(*                Cosimo Perini Brogi, Leonardo Quartini 2024.               *)
(* (c) Copyright, Antonella Bilotta, Marco Maggesi,                          *)
(*                Cosimo Perini Brogi 2025.                                  *)
(* ========================================================================= *)

(* ------------------------------------------------------------------------- *)
(* Libraries.                                                                *)
(* ------------------------------------------------------------------------- *)

needs "Library/card.ml";;                (* Cardinality                      *)
needs "Library/rstc.ml";;                (* Refl, sym, trans closure         *)

(* ------------------------------------------------------------------------- *)
(* Syntax, semantics and calculus.                                           *)
(* ------------------------------------------------------------------------- *)

loadt "HOLMS/misc.ml";;                (* Miscellanea                        *)
loadt "HOLMS/modal.ml";;               (* Syntax and semantics               *)
loadt "HOLMS/calculus.ml";;            (* Axiomatic calculus                 *)

(* ------------------------------------------------------------------------- *)
(* Correspondence Theory.                                                    *)
(* ------------------------------------------------------------------------- *)

loadt "HOLMS/ad_hoc_correspondence.ml";;       (* Ad hoc polimorphic code    *)
loadt "HOLMS/parametric_correspondence.ml";;   (* Parametric code            *)

(* ------------------------------------------------------------------------- *)
(* Meta-theory.                                                              *)
(* ------------------------------------------------------------------------- *)

loadt "HOLMS/conjlist.ml";;            (* Iterated conjunctions              *)
loadt "HOLMS/consistent.ml";;          (* Consistent sets of formulae        *)
loadt "HOLMS/gen_completeness.ml";;    (* Lemmata about completeness         *)
loadt "HOLMS/k_completeness.ml";;      (* Completeness of K                  *)
loadt "HOLMS/t_completeness.ml";;      (* Completeness of T                  *)
loadt "HOLMS/k4_completeness.ml";;     (* Completeness of K4                 *)
loadt "HOLMS/s4_completeness.ml";;     (* Completeness of S4                 *)
loadt "HOLMS/b_completeness.ml";;      (* Completeness of B                  *)
loadt "HOLMS/s5_completeness.ml";;     (* Completeness of S5                 *)
loadt "HOLMS/gl_completeness.ml";;     (* Completeness of GL                 *)

(* ------------------------------------------------------------------------- *)
(* Decision procedures.                                                      *)
(* ------------------------------------------------------------------------- *)

loadt "HOLMS/gen_decid.ml";;           (* Tools for decidability             *)
loadt "HOLMS/gen_countermodel.ml";;    (* Tools for countermodels            *)
loadt "HOLMS/k_decid.ml";;             (* Semidecision procedure for K       *)
loadt "HOLMS/t_decid.ml";;             (* Semidecision procedure for T       *)
loadt "HOLMS/k4_decid.ml";;            (* Semidecision procedure for K4      *)
loadt "HOLMS/s4_decid.ml";;            (* Semidecision procedure for S4      *)
loadt "HOLMS/b_decid.ml";;             (* Semidecision procedure for B       *)
loadt "HOLMS/s5_decid.ml";;            (* Semidecision procedure for S5      *)
loadt "HOLMS/gl_decid.ml";;            (* Semidecision procedure for GL      *)
