import HOLMS.Modal

/-!
# Axiomatic calculus for normal modal logics

This module defines the Hilbert basis for `K` and derivability from a set of
additional axioms and a set of hypotheses. The modal rule is necessitation
from the empty set of hypotheses. Derivability is written `S ⊢ₘ[H] p`.
-/

namespace HOLMS

open ModalNotation

/-- The primitive Hilbert axiom schemata for normal modal logic `K`. -/
-- HOL: `KAXIOM`, introduced by `KAXIOM_RULES` (`calculus.ml`).
inductive KAxiom : Form → Prop where
  -- HOL: `KAXIOM_RULES`, clause 1. See `calculus.ml`.
  | addImp (p q) : KAxiom (p ⟶ (q ⟶ p))
  -- HOL: `KAXIOM_RULES`, clause 2. See `calculus.ml`.
  | distribImp (p q r) : KAxiom ((p ⟶ q ⟶ r) ⟶ (p ⟶ q) ⟶ (p ⟶ r))
  -- HOL: `KAXIOM_RULES`, clause 3. See `calculus.ml`.
  | doubleNeg (p) : KAxiom (((p ⟶ ⊥ₘ) ⟶ ⊥ₘ) ⟶ p)
  -- HOL: `KAXIOM_RULES`, clause 4. See `calculus.ml`.
  | iffImp₁ (p q) : KAxiom ((p ⟷ q) ⟶ p ⟶ q)
  -- HOL: `KAXIOM_RULES`, clause 5. See `calculus.ml`.
  | iffImp₂ (p q) : KAxiom ((p ⟷ q) ⟶ q ⟶ p)
  -- HOL: `KAXIOM_RULES`, clause 6. See `calculus.ml`.
  | impIff (p q) : KAxiom ((p ⟶ q) ⟶ (q ⟶ p) ⟶ (p ⟷ q))
  -- HOL: `KAXIOM_RULES`, clause 7. See `calculus.ml`.
  | verum : KAxiom (⊤ₘ ⟷ (⊥ₘ ⟶ ⊥ₘ))
  -- HOL: `KAXIOM_RULES`, clause 8. See `calculus.ml`.
  | neg (p) : KAxiom ((¬p) ⟷ (p ⟶ ⊥ₘ))
  -- HOL: `KAXIOM_RULES`, clause 9. See `calculus.ml`.
  | conj (p q) : KAxiom ((p ⋏ q) ⟷ ((p ⟶ q ⟶ ⊥ₘ) ⟶ ⊥ₘ))
  -- HOL: `KAXIOM_RULES`, clause 10. See `calculus.ml`.
  | disj (p q) : KAxiom ((p ⋎ q) ⟷ (¬((¬p) ⋏ (¬q))))
  -- HOL: `KAXIOM_RULES`, clause 11. See `calculus.ml`.
  | boxImp (p q) : KAxiom (□(p ⟶ q) ⟶ □p ⟶ □q)

/-- Derivability in the normal modal logic generated by `S`, under hypotheses
`H`. -/
-- HOL: the derivability judgment `[S . H |~ p]`, introduced by `MODPROVES_RULES` (`calculus.ml`).
inductive ModProves (S : Set Form) : Set Form → Form → Prop where
  -- HOL: `MODPROVES_RULES`, clause 1 (`MODPROVES_KAXIOM`). See `calculus.ml`.
  | kaxiom {H p} : KAxiom p → ModProves S H p
  -- HOL: `MODPROVES_RULES`, clause 2 (`MODPROVES_AX`). See `calculus.ml`.
  | ax {H p} : p ∈ S → ModProves S H p
  -- HOL: `MODPROVES_RULES`, clause 3 (`MODPROVES_HP`). See `calculus.ml`.
  | hyp {H p} : p ∈ H → ModProves S H p
  -- HOL: `MODPROVES_RULES`, clause 4 (`MLK_modusponens`). See `calculus.ml`.
  | modusPonens {H p q} : ModProves S H (p ⟶ q) → ModProves S H p →
      ModProves S H q
  -- HOL: `MODPROVES_RULES`, clause 5 (`MLK_necessitation`). See `calculus.ml`.
  | necessitation {H p} : ModProves S ∅ p → ModProves S H (□p)

namespace ModalNotation

-- HOL: `[S . H |~ p]` notation (`calculus.ml`); scoped Lean notation.
scoped notation:45 S " ⊢ₘ[" H "] " p => ModProves S H p

end ModalNotation

open ModalNotation

/-- Introduce a primitive `K` axiom. -/
-- HOL: `MODPROVES_KAXIOM` (`calculus.ml`).
theorem MODPROVES_KAXIOM {S H : Set Form} {p : Form} (h : KAxiom p) :
    S ⊢ₘ[H] p := .kaxiom h

/-- Introduce an axiom from the parameter set. -/
-- HOL: `MODPROVES_AX` (`calculus.ml`).
theorem MODPROVES_AX {S H : Set Form} {p : Form} (h : p ∈ S) :
    S ⊢ₘ[H] p := .ax h

/-- Introduce a hypothesis. -/
-- HOL: `MODPROVES_HP` (`calculus.ml`).
theorem MODPROVES_HP {S H : Set Form} {p : Form} (h : p ∈ H) :
    S ⊢ₘ[H] p := .hyp h

/-- Modus ponens. -/
-- HOL: `MLK_modusponens` (`calculus.ml`).
theorem MLK_modusponens {S H : Set Form} {p q : Form}
    (hpq : S ⊢ₘ[H] p ⟶ q) (hp : S ⊢ₘ[H] p) : S ⊢ₘ[H] q :=
  .modusPonens hpq hp

/-- Necessitation is permitted only for a theorem with no hypotheses. -/
-- HOL: `MLK_necessitation` (`calculus.ml`).
theorem MLK_necessitation {S H : Set Form} {p : Form}
    (hp : S ⊢ₘ[(∅ : Set Form)] p) : S ⊢ₘ[H] □p :=
  .necessitation hp

/-! ## Named primitive axioms -/

-- HOL: `MLK_axiom_addimp` (`calculus.ml`).
theorem MLK_axiom_addimp {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] p ⟶ (q ⟶ p) := .kaxiom (.addImp p q)

-- HOL: `MLK_axiom_distribimp` (`calculus.ml`).
theorem MLK_axiom_distribimp {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] (p ⟶ q ⟶ r) ⟶ (p ⟶ q) ⟶ (p ⟶ r) :=
  .kaxiom (.distribImp p q r)

-- HOL: `MLK_axiom_doubleneg` (`calculus.ml`).
theorem MLK_axiom_doubleneg {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] ((p ⟶ ⊥ₘ) ⟶ ⊥ₘ) ⟶ p := .kaxiom (.doubleNeg p)

-- HOL: `MLK_axiom_iffimp1` (`calculus.ml`).
theorem MLK_axiom_iffimp1 {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟷ q) ⟶ p ⟶ q := .kaxiom (.iffImp₁ p q)

-- HOL: `MLK_axiom_iffimp2` (`calculus.ml`).
theorem MLK_axiom_iffimp2 {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟷ q) ⟶ q ⟶ p := .kaxiom (.iffImp₂ p q)

-- HOL: `MLK_axiom_impiff` (`calculus.ml`).
theorem MLK_axiom_impiff {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟶ q) ⟶ (q ⟶ p) ⟶ (p ⟷ q) :=
  .kaxiom (.impIff p q)

-- HOL: `MLK_axiom_true` (`calculus.ml`).
theorem MLK_axiom_true {S H : Set Form} :
    S ⊢ₘ[H] ⊤ₘ ⟷ (⊥ₘ ⟶ ⊥ₘ) := .kaxiom .verum

-- HOL: `MLK_axiom_not` (`calculus.ml`).
theorem MLK_axiom_not {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] (¬p) ⟷ (p ⟶ ⊥ₘ) := .kaxiom (.neg p)

-- HOL: `MLK_axiom_and` (`calculus.ml`).
theorem MLK_axiom_and {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⋏ q) ⟷ ((p ⟶ q ⟶ ⊥ₘ) ⟶ ⊥ₘ) :=
  .kaxiom (.conj p q)

-- HOL: `MLK_axiom_or` (`calculus.ml`).
theorem MLK_axiom_or {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⋎ q) ⟷ (¬((¬p) ⋏ (¬q))) := .kaxiom (.disj p q)

-- HOL: `MLK_axiom_boximp` (`calculus.ml`).
theorem MLK_axiom_boximp {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] □(p ⟶ q) ⟶ □p ⟶ □q := .kaxiom (.boxImp p q)

/-! ## Monotonicity -/

/-- Derivability is monotone in the set of additional axioms. -/
-- HOL: `MODPROVES_MONO1` (`calculus.ml`).
theorem MODPROVES_MONO1 {S S' H : Set Form} {p : Form} (hSS' : S ⊆ S')
    (hp : S ⊢ₘ[H] p) : S' ⊢ₘ[H] p := by
  induction hp with
  | kaxiom h => exact .kaxiom h
  | ax h => exact .ax (hSS' h)
  | hyp h => exact .hyp h
  | modusPonens _ _ ihpq ihp => exact .modusPonens ihpq ihp
  | necessitation _ ih => exact .necessitation ih

/-- Derivability is monotone in the set of hypotheses. -/
-- HOL: `MODPROVES_MONO2` (`calculus.ml`).
theorem MODPROVES_MONO2 {S H H' : Set Form} {p : Form} (hp : S ⊢ₘ[H] p)
    (hHH' : H ⊆ H') : S ⊢ₘ[H'] p := by
  induction hp with
  | kaxiom h => exact .kaxiom h
  | ax h => exact .ax h
  | hyp h => exact .hyp (hHH' h)
  | modusPonens _ _ ihpq ihp => exact .modusPonens (ihpq hHH') (ihp hHH')
  | necessitation h _ => exact .necessitation h

/-! ## Basic derived implicational rules -/

-- HOL: `MLK_iff_imp1` (`calculus.ml`).
theorem MLK_iff_imp1 {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] p ⟷ q) : S ⊢ₘ[H] p ⟶ q :=
  MLK_modusponens (MLK_axiom_iffimp1 p q) h

-- HOL: `MLK_iff_imp2` (`calculus.ml`).
theorem MLK_iff_imp2 {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] p ⟷ q) : S ⊢ₘ[H] q ⟶ p :=
  MLK_modusponens (MLK_axiom_iffimp2 p q) h

-- HOL: `MLK_imp_antisym` (`calculus.ml`).
theorem MLK_imp_antisym {S H : Set Form} {p q : Form}
    (hpq : S ⊢ₘ[H] p ⟶ q) (hqp : S ⊢ₘ[H] q ⟶ p) :
    S ⊢ₘ[H] p ⟷ q :=
  MLK_modusponens (MLK_modusponens (MLK_axiom_impiff p q) hpq) hqp

-- HOL: `MLK_add_assum` (`calculus.ml`).
theorem MLK_add_assum {S H : Set Form} (p : Form) {q : Form}
    (hq : S ⊢ₘ[H] q) : S ⊢ₘ[H] p ⟶ q :=
  MLK_modusponens (MLK_axiom_addimp q p) hq

-- HOL: `MLK_imp_refl_th` (`calculus.ml`).
theorem MLK_imp_refl_th {S H : Set Form} (p : Form) : S ⊢ₘ[H] p ⟶ p := by
  exact MLK_modusponens
    (MLK_modusponens (MLK_axiom_distribimp p (p ⟶ p) p)
      (MLK_axiom_addimp p (p ⟶ p)))
    (MLK_axiom_addimp p p)

-- HOL: `MLK_imp_add_assum` (`calculus.ml`).
theorem MLK_imp_add_assum {S H : Set Form} (p : Form) {q r : Form}
    (h : S ⊢ₘ[H] q ⟶ r) : S ⊢ₘ[H] (p ⟶ q) ⟶ (p ⟶ r) :=
  MLK_modusponens (MLK_axiom_distribimp p q r) (MLK_add_assum p h)

-- HOL: `MLK_imp_unduplicate` (`calculus.ml`).
theorem MLK_imp_unduplicate {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] p ⟶ p ⟶ q) : S ⊢ₘ[H] p ⟶ q :=
  MLK_modusponens (MLK_modusponens (MLK_axiom_distribimp p p q) h)
    (MLK_imp_refl_th p)

-- HOL: `MLK_imp_trans` (`calculus.ml`).
theorem MLK_imp_trans {S H : Set Form} {p q r : Form}
    (hpq : S ⊢ₘ[H] p ⟶ q) (hqr : S ⊢ₘ[H] q ⟶ r) :
    S ⊢ₘ[H] p ⟶ r :=
  MLK_modusponens (MLK_imp_add_assum p hqr) hpq

-- HOL: `MLK_imp_swap` (`calculus.ml`).
theorem MLK_imp_swap {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] p ⟶ q ⟶ r) : S ⊢ₘ[H] q ⟶ p ⟶ r := by
  have h₁ : S ⊢ₘ[H] (p ⟶ q) ⟶ (p ⟶ r) :=
    MLK_modusponens (MLK_axiom_distribimp p q r) h
  exact MLK_imp_trans (MLK_axiom_addimp q p) h₁

-- HOL: `MLK_imp_trans_chain_2` (`calculus.ml`).
theorem MLK_imp_trans_chain_2 {S H : Set Form} {p q₁ q₂ r : Form}
    (hpq₁ : S ⊢ₘ[H] p ⟶ q₁) (hpq₂ : S ⊢ₘ[H] p ⟶ q₂)
    (hqr : S ⊢ₘ[H] q₁ ⟶ q₂ ⟶ r) : S ⊢ₘ[H] p ⟶ r := by
  apply MLK_imp_unduplicate
  have h₁ : S ⊢ₘ[H] p ⟶ q₁ ⟶ r :=
    MLK_imp_trans hpq₂ (MLK_imp_swap hqr)
  exact MLK_imp_trans hpq₁ (MLK_imp_swap h₁)

-- HOL: `MLK_imp_trans_th` (`calculus.ml`).
theorem MLK_imp_trans_th {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] (q ⟶ r) ⟶ (p ⟶ q) ⟶ (p ⟶ r) := by
  exact MLK_imp_trans (MLK_axiom_addimp (q ⟶ r) p)
    (MLK_axiom_distribimp p q r)

-- HOL: `GLimp_add_concl` (`calculus.ml`).
theorem GLimp_add_concl {S H : Set Form} {p q : Form} (r : Form)
    (hpq : S ⊢ₘ[H] p ⟶ q) : S ⊢ₘ[H] (q ⟶ r) ⟶ (p ⟶ r) :=
  MLK_modusponens (MLK_imp_swap (MLK_imp_trans_th p q r)) hpq

-- HOL: `MLK_imp_trans2` (`calculus.ml`).
theorem MLK_imp_trans2 {S H : Set Form} {p q r s : Form}
    (hpqr : S ⊢ₘ[H] p ⟶ q ⟶ r) (hrs : S ⊢ₘ[H] r ⟶ s) :
    S ⊢ₘ[H] p ⟶ q ⟶ s :=
  MLK_imp_trans hpqr (MLK_imp_add_assum q hrs)

/-! ## Deduction theorem

It is established early because it is the natural Lean interface for proving
the remaining derived Hilbert schemata.
-/

-- HOL: `MODPROVES_DEDUCTION_LEMMA_INSERT` (`calculus.ml`).
theorem MODPROVES_DEDUCTION_LEMMA_INSERT {S H : Set Form} {p q : Form}
    (hpq : S ⊢ₘ[H] p ⟶ q) : S ⊢ₘ[insert p H] q := by
  apply MLK_modusponens
  · exact MODPROVES_MONO2 hpq (Set.subset_insert p H)
  · exact .hyp (Set.mem_insert p H)

-- HOL: `MODPROVES_DEDUCTION_LEMMA_DELETE` (`calculus.ml`).
theorem MODPROVES_DEDUCTION_LEMMA_DELETE {S H : Set Form} {p q : Form}
    (hq : S ⊢ₘ[H] q) (hp : p ∈ H) : S ⊢ₘ[H \ {p}] p ⟶ q := by
  induction hq with
  | kaxiom h => exact MLK_add_assum p (.kaxiom h)
  | ax h => exact MLK_add_assum p (.ax h)
  | @hyp _ q hq =>
      by_cases h : q = p
      · subst q
        exact MLK_imp_refl_th p
      · exact MLK_add_assum p (.hyp ⟨hq, h⟩)
  | @modusPonens _ a b hab ha ihab iha =>
      exact MLK_modusponens (MLK_modusponens (MLK_axiom_distribimp p a b)
        (ihab hp)) (iha hp)
  | @necessitation _ a ha _ =>
      exact MLK_add_assum p (.necessitation ha)

/-- The deduction theorem for sets of hypotheses. -/
-- HOL: `MODPROVES_DEDUCTION_LEMMA` (`calculus.ml`).
theorem MODPROVES_DEDUCTION_LEMMA {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] p ⟶ q) ↔ (S ⊢ₘ[insert p H] q) := by
  constructor
  · exact MODPROVES_DEDUCTION_LEMMA_INSERT
  · intro hq
    by_cases hp : p ∈ H
    · have hi : insert p H = H := Set.insert_eq_of_mem hp
      rw [hi] at hq
      exact MLK_add_assum p hq
    · have hdel : insert p H \ {p} = H := by
        ext x
        simp only [Set.mem_sdiff, Set.mem_insert_iff, Set.mem_singleton_iff]
        constructor
        · rintro ⟨hx | hx, hne⟩
          · exact (hne hx).elim
          · exact hx
        · intro hx
          exact ⟨Or.inr hx, fun hxp => hp (hxp ▸ hx)⟩
      simpa [hdel] using
        (MODPROVES_DEDUCTION_LEMMA_DELETE hq (Set.mem_insert p H))

-- HOL: `MLK_imp_swap_th` (`calculus.ml`).
theorem MLK_imp_swap_th {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] (p ⟶ q ⟶ r) ⟶ (q ⟶ p ⟶ r) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  exact MLK_imp_swap (.hyp (Set.mem_insert _ _))

-- HOL: `MLK_imp_insert` (`calculus.ml`).
theorem MLK_imp_insert {S H : Set Form} (q : Form) {p r : Form}
    (h : S ⊢ₘ[H] p ⟶ r) : S ⊢ₘ[H] p ⟶ q ⟶ r :=
  MLK_imp_trans h (MLK_axiom_addimp r q)

/-! ## Some further basic rules -/

-- HOL: `MLK_ex_falso_th` (`calculus.ml`).
theorem MLK_ex_falso_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] ⊥ₘ ⟶ p :=
  MLK_imp_trans (MLK_axiom_addimp ⊥ₘ (p ⟶ ⊥ₘ))
    (MLK_axiom_doubleneg p)

-- HOL: `MLK_ex_falso` (`calculus.ml`).
theorem MLK_ex_falso {S H : Set Form} {p : Form} (h : S ⊢ₘ[H] ⊥ₘ) :
    S ⊢ₘ[H] p := MLK_modusponens (MLK_ex_falso_th p) h

-- HOL: `MLK_imp_contr_th` (`calculus.ml`).
theorem MLK_imp_contr_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟶ ⊥ₘ) ⟶ p ⟶ q :=
  MLK_imp_add_assum p (MLK_ex_falso_th q)

-- HOL: `MLK_contrad` (`calculus.ml`).
theorem MLK_contrad {S H : Set Form} {p : Form}
    (h : S ⊢ₘ[H] (p ⟶ ⊥ₘ) ⟶ p) : S ⊢ₘ[H] p := by
  apply MLK_modusponens (MLK_axiom_doubleneg p)
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  have hn : S ⊢ₘ[insert (p ⟶ ⊥ₘ) H] p ⟶ ⊥ₘ := .hyp (Set.mem_insert _ _)
  have hp : S ⊢ₘ[insert (p ⟶ ⊥ₘ) H] p :=
    MLK_modusponens (MODPROVES_MONO2 h (Set.subset_insert _ _)) hn
  exact MLK_modusponens hn hp

-- HOL: `MLK_bool_cases` (`calculus.ml`).
theorem MLK_bool_cases {S H : Set Form} {p q : Form}
    (hp : S ⊢ₘ[H] p ⟶ q) (hnp : S ⊢ₘ[H] (p ⟶ ⊥ₘ) ⟶ q) :
    S ⊢ₘ[H] q := by
  apply MLK_modusponens (MLK_axiom_doubleneg q)
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K := insert (q ⟶ ⊥ₘ) H
  have hnq : S ⊢ₘ[K] q ⟶ ⊥ₘ := .hyp (by simp [K])
  have hnp' : S ⊢ₘ[K] p ⟶ ⊥ₘ :=
    MLK_imp_trans (MODPROVES_MONO2 hp (Set.subset_insert _ _)) hnq
  have hq : S ⊢ₘ[K] q := MLK_modusponens
    (MODPROVES_MONO2 hnp (Set.subset_insert _ _)) hnp'
  exact MLK_modusponens hnq hq

-- HOL: `MLK_truth_th` (`calculus.ml`).
theorem MLK_truth_th {S H : Set Form} : S ⊢ₘ[H] ⊤ₘ := by
  apply MLK_modusponens (MLK_iff_imp2 (MLK_axiom_true (S := S) (H := H)))
  exact MLK_imp_refl_th ⊥ₘ

-- HOL: `MLK_iff_refl_th` (`calculus.ml`).
theorem MLK_iff_refl_th {S H : Set Form} (p : Form) : S ⊢ₘ[H] p ⟷ p :=
  MLK_imp_antisym (MLK_imp_refl_th p) (MLK_imp_refl_th p)

-- HOL: `MLK_iff_sym` (`calculus.ml`).
theorem MLK_iff_sym {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] p ⟷ q) : S ⊢ₘ[H] q ⟷ p :=
  MLK_imp_antisym (MLK_iff_imp2 h) (MLK_iff_imp1 h)

-- HOL: `MLK_iff_trans` (`calculus.ml`).
theorem MLK_iff_trans {S H : Set Form} {p q r : Form}
    (hpq : S ⊢ₘ[H] p ⟷ q) (hqr : S ⊢ₘ[H] q ⟷ r) :
    S ⊢ₘ[H] p ⟷ r :=
  MLK_imp_antisym (MLK_imp_trans (MLK_iff_imp1 hpq) (MLK_iff_imp1 hqr))
    (MLK_imp_trans (MLK_iff_imp2 hqr) (MLK_iff_imp2 hpq))

-- HOL: `MLK_imp_box` (`calculus.ml`).
theorem MLK_imp_box {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[(∅ : Set Form)] p ⟶ q) : S ⊢ₘ[H] □p ⟶ □q :=
  MLK_modusponens (MLK_axiom_boximp p q) (MLK_necessitation h)

-- HOL: `MLK_box_moduspones` (source spelling) (`calculus.ml`).
theorem MLK_box_modusponens {S H : Set Form} {p q : Form}
    (hpq : S ⊢ₘ[H] □(p ⟶ q)) (hp : S ⊢ₘ[H] □p) : S ⊢ₘ[H] □q :=
  MLK_modusponens (MLK_modusponens (MLK_axiom_boximp p q) hpq) hp

-- HOL: `MLK_boximp` (`calculus.ml`).
theorem MLK_boximp {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] □(p ⟶ q)) : S ⊢ₘ[H] □p ⟶ □q :=
  MLK_modusponens (MLK_axiom_boximp p q) h

-- HOL: `MLK_box_moduspones` (`calculus.ml`).
theorem MLK_box_moduspones {S H : Set Form} {p q : Form}
    (hpq : S ⊢ₘ[(∅ : Set Form)] p ⟶ q) (hp : S ⊢ₘ[H] □p) :
    S ⊢ₘ[H] □q := MLK_modusponens (MLK_imp_box hpq) hp

/-! ## Conjunction -/

-- HOL: `MLK_and_left_th` (`calculus.ml`).
theorem MLK_and_left_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⋏ q) ⟶ p := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MLK_modusponens (MLK_axiom_doubleneg p)
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K := insert (p ⟶ ⊥ₘ) (insert (p ⋏ q) H)
  have ha : S ⊢ₘ[K] p ⋏ q := .hyp (by simp [K])
  have hb : S ⊢ₘ[K] (p ⟶ q ⟶ ⊥ₘ) ⟶ ⊥ₘ :=
    MLK_modusponens (MLK_iff_imp1 (MLK_axiom_and p q)) ha
  have hpqf : S ⊢ₘ[K] p ⟶ q ⟶ ⊥ₘ := by
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    have hn : S ⊢ₘ[insert q (insert p K)] p ⟶ ⊥ₘ := .hyp (by simp [K])
    have hp : S ⊢ₘ[insert q (insert p K)] p := .hyp (by simp)
    exact MLK_modusponens hn hp
  exact MLK_modusponens hb hpqf

-- HOL: `MLK_and_right_th` (`calculus.ml`).
theorem MLK_and_right_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⋏ q) ⟶ q := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MLK_modusponens (MLK_axiom_doubleneg q)
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K := insert (q ⟶ ⊥ₘ) (insert (p ⋏ q) H)
  have ha : S ⊢ₘ[K] p ⋏ q := .hyp (by simp [K])
  have hb : S ⊢ₘ[K] (p ⟶ q ⟶ ⊥ₘ) ⟶ ⊥ₘ :=
    MLK_modusponens (MLK_iff_imp1 (MLK_axiom_and p q)) ha
  have hpqf : S ⊢ₘ[K] p ⟶ q ⟶ ⊥ₘ := by
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    have hn : S ⊢ₘ[insert q (insert p K)] q ⟶ ⊥ₘ := .hyp (by simp [K])
    have hq : S ⊢ₘ[insert q (insert p K)] q := .hyp (by simp)
    exact MLK_modusponens hn hq
  exact MLK_modusponens hb hpqf

-- HOL: `MLK_and_pair_th` (`calculus.ml`).
theorem MLK_and_pair_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] p ⟶ q ⟶ p ⋏ q := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MLK_modusponens (MLK_iff_imp2 (MLK_axiom_and p q))
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K := insert (p ⟶ q ⟶ ⊥ₘ) (insert q (insert p H))
  have h : S ⊢ₘ[K] p ⟶ q ⟶ ⊥ₘ := .hyp (by simp [K])
  have hp : S ⊢ₘ[K] p := .hyp (by simp [K])
  have hq : S ⊢ₘ[K] q := .hyp (by simp [K])
  exact MLK_modusponens (MLK_modusponens h hp) hq

-- HOL: `MLK_and` (`calculus.ml`).
theorem MLK_and {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] p ⋏ q) ↔ (S ⊢ₘ[H] p) ∧ (S ⊢ₘ[H] q) := by
  constructor
  · intro h
    exact ⟨MLK_modusponens (MLK_and_left_th p q) h,
      MLK_modusponens (MLK_and_right_th p q) h⟩
  · rintro ⟨hp, hq⟩
    exact MLK_modusponens (MLK_modusponens (MLK_and_pair_th p q) hp) hq

-- HOL: `MLK_and_intro` (`calculus.ml`).
theorem MLK_and_intro {S H : Set Form} {p q r : Form}
    (hpq : S ⊢ₘ[H] p ⟶ q) (hpr : S ⊢ₘ[H] p ⟶ r) :
    S ⊢ₘ[H] p ⟶ q ⋏ r :=
  MLK_imp_trans_chain_2 hpq hpr (MLK_and_pair_th q r)

-- HOL: `MLK_and_elim` (`calculus.ml`).
theorem MLK_and_elim {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] r ⟶ p ⋏ q) :
    (S ⊢ₘ[H] r ⟶ q) ∧ (S ⊢ₘ[H] r ⟶ p) :=
  ⟨MLK_imp_trans h (MLK_and_right_th p q),
    MLK_imp_trans h (MLK_and_left_th p q)⟩

-- HOL: `MLK_and_add` (`calculus.ml`).
theorem MLK_and_add {S H : Set Form} {p q r : Form}
    (hrq : S ⊢ₘ[H] r ⟶ q) (hrp : S ⊢ₘ[H] r ⟶ p) :
    S ⊢ₘ[H] r ⟶ p ⋏ q := MLK_and_intro hrp hrq

-- HOL: `MLK_shunt` (`calculus.ml`).
theorem MLK_shunt {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] p ⋏ q ⟶ r) : S ⊢ₘ[H] p ⟶ q ⟶ r :=
  MLK_imp_trans2 (MLK_and_pair_th p q) h

-- HOL: `MLK_ante_conj` (`calculus.ml`).
theorem MLK_ante_conj {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] p ⟶ q ⟶ r) : S ⊢ₘ[H] p ⋏ q ⟶ r :=
  MLK_imp_trans_chain_2 (MLK_and_left_th p q) (MLK_and_right_th p q) h

-- HOL: `MLK_ante_conj2` (`calculus.ml`).
theorem MLK_ante_conj2 {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] q ⟶ p ⟶ r) : S ⊢ₘ[H] p ⋏ q ⟶ r :=
  MLK_ante_conj (MLK_imp_swap h)

-- HOL: `MLK_modusponens_th` (`calculus.ml`).
theorem MLK_modusponens_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] ((p ⟶ q) ⋏ p) ⟶ q :=
  MLK_ante_conj (MLK_imp_refl_th (p ⟶ q))

-- HOL: `MLK_iff_def_th` (`calculus.ml`).
theorem MLK_iff_def_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟷ q) ⟷ ((p ⟶ q) ⋏ (q ⟶ p)) := by
  apply MLK_imp_antisym
  · exact MLK_and_intro (MLK_axiom_iffimp1 p q) (MLK_axiom_iffimp2 p q)
  · exact MLK_ante_conj (MLK_axiom_impiff p q)

-- HOL: `MLK_iff_def` (`calculus.ml`).
theorem MLK_iff_def {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] p ⟷ q) ↔ (S ⊢ₘ[H] p ⟶ q) ∧ (S ⊢ₘ[H] q ⟶ p) := by
  constructor
  · intro h; exact ⟨MLK_iff_imp1 h, MLK_iff_imp2 h⟩
  · rintro ⟨h₁, h₂⟩; exact MLK_imp_antisym h₁ h₂

/-! ## Negation and disjunction -/

-- HOL: `MLK_not_def` (`calculus.ml`).
theorem MLK_not_def {S H : Set Form} {p : Form} :
    (S ⊢ₘ[H] ¬p) ↔ (S ⊢ₘ[H] p ⟶ ⊥ₘ) := by
  constructor
  · exact fun h => MLK_modusponens (MLK_iff_imp1 (MLK_axiom_not p)) h
  · exact fun h => MLK_modusponens (MLK_iff_imp2 (MLK_axiom_not p)) h

-- HOL: `MLK_not_false` (`calculus.ml`).
theorem MLK_not_false (S : Set Form) : S ⊢ₘ[(∅ : Set Form)] ¬⊥ₘ :=
  MLK_not_def.mpr (MLK_imp_refl_th ⊥ₘ)

-- HOL: `MLK_contrapos` (`calculus.ml`).
theorem MLK_contrapos {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] p ⟶ q) : S ⊢ₘ[H] (¬q) ⟶ (¬p) :=
  MLK_imp_trans (MLK_iff_imp1 (MLK_axiom_not q)) <|
    MLK_imp_trans (GLimp_add_concl ⊥ₘ h)
      (MLK_iff_imp2 (MLK_axiom_not p))

-- HOL: `MLK_not_not_false_th` (`calculus.ml`).
theorem MLK_not_not_false_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] ((p ⟶ ⊥ₘ) ⟶ ⊥ₘ) ⟷ p := by
  apply MLK_imp_antisym
  · exact MLK_axiom_doubleneg p
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    have hn : S ⊢ₘ[insert (p ⟶ ⊥ₘ) (insert p H)] p ⟶ ⊥ₘ := .hyp (by simp)
    have hp : S ⊢ₘ[insert (p ⟶ ⊥ₘ) (insert p H)] p := .hyp (by simp)
    exact MLK_modusponens hn hp

-- HOL: `MLK_not_not_th` (`calculus.ml`).
theorem MLK_not_not_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] (¬(¬p)) ⟷ p := by
  apply MLK_imp_antisym
  · exact MLK_imp_trans (MLK_iff_imp1 (MLK_axiom_not (¬p))) <|
      MLK_imp_trans (GLimp_add_concl ⊥ₘ (MLK_iff_imp2 (MLK_axiom_not p)))
        (MLK_axiom_doubleneg p)
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MLK_modusponens (MLK_iff_imp2 (MLK_axiom_not (¬p)))
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    have hp : S ⊢ₘ[insert (¬p) (insert p H)] p := .hyp (by simp)
    have hnp : S ⊢ₘ[insert (¬p) (insert p H)] p ⟶ ⊥ₘ :=
      MLK_modusponens (MLK_iff_imp1 (MLK_axiom_not p)) (.hyp (by simp))
    exact MLK_modusponens hnp hp

-- HOL: `MLK_DOUBLENEG_CL` (`calculus.ml`).
theorem MLK_DOUBLENEG_CL {S H : Set Form} {p : Form}
    (h : S ⊢ₘ[H] ¬(¬p)) : S ⊢ₘ[H] p :=
  MLK_modusponens (MLK_iff_imp1 (MLK_not_not_th p)) h

-- HOL: `MLK_DOUBLENEG` (`calculus.ml`).
theorem MLK_DOUBLENEG {S H : Set Form} {p : Form}
    (h : S ⊢ₘ[H] p) : S ⊢ₘ[H] ¬(¬p) :=
  MLK_modusponens (MLK_iff_imp2 (MLK_not_not_th p)) h

-- HOL: `MLK_DOUBLENEG_IFF` (`calculus.ml`).
theorem MLK_DOUBLENEG_IFF {S H : Set Form} {p : Form} :
    (S ⊢ₘ[H] ¬(¬p)) ↔ (S ⊢ₘ[H] p) := ⟨MLK_DOUBLENEG_CL, MLK_DOUBLENEG⟩

-- HOL: `MLK_or_right_th` (`calculus.ml`).
theorem MLK_or_right_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] p ⟶ p ⋎ q := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MLK_modusponens (MLK_iff_imp2 (MLK_axiom_or p q))
  apply MLK_modusponens (MLK_iff_imp2 (MLK_axiom_not ((¬p) ⋏ (¬q))))
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  have hp : S ⊢ₘ[insert ((¬p) ⋏ (¬q)) (insert p H)] p := .hyp (by simp)
  have hnp : S ⊢ₘ[insert ((¬p) ⋏ (¬q)) (insert p H)] ¬p :=
    MLK_modusponens (MLK_and_left_th (¬p) (¬q)) (.hyp (by simp))
  exact MLK_modusponens (MLK_not_def.mp hnp) hp

-- HOL: `MLK_or_left_th` (`calculus.ml`).
theorem MLK_or_left_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] q ⟶ p ⋎ q := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MLK_modusponens (MLK_iff_imp2 (MLK_axiom_or p q))
  apply MLK_modusponens (MLK_iff_imp2 (MLK_axiom_not ((¬p) ⋏ (¬q))))
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  have hq : S ⊢ₘ[insert ((¬p) ⋏ (¬q)) (insert q H)] q := .hyp (by simp)
  have hnq : S ⊢ₘ[insert ((¬p) ⋏ (¬q)) (insert q H)] ¬q :=
    MLK_modusponens (MLK_and_right_th (¬p) (¬q)) (.hyp (by simp))
  exact MLK_modusponens (MLK_not_def.mp hnq) hq

-- HOL: `MLK_or_introl` (`calculus.ml`).
theorem MLK_or_introl {S H : Set Form} {p : Form} (q : Form)
    (h : S ⊢ₘ[H] p) : S ⊢ₘ[H] p ⋎ q :=
  MLK_modusponens (MLK_or_right_th p q) h

-- HOL: `MLK_or_intror` (`calculus.ml`).
theorem MLK_or_intror {S H : Set Form} (p : Form) {q : Form}
    (h : S ⊢ₘ[H] q) : S ⊢ₘ[H] p ⋎ q :=
  MLK_modusponens (MLK_or_left_th p q) h

-- HOL: `MLK_ante_disj` (`calculus.ml`).
theorem MLK_ante_disj {S H : Set Form} {p q r : Form}
    (hpr : S ⊢ₘ[H] p ⟶ r) (hqr : S ⊢ₘ[H] q ⟶ r) :
    S ⊢ₘ[H] p ⋎ q ⟶ r := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K := insert (p ⋎ q) H
  apply MLK_bool_cases (p := p)
  · exact MODPROVES_MONO2 hpr (Set.subset_insert _ _)
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    let L := insert (p ⟶ ⊥ₘ) K
    apply MLK_bool_cases (p := q)
    · exact MODPROVES_MONO2 hqr (by intro x hx; simp [hx])
    · apply MODPROVES_DEDUCTION_LEMMA.mpr
      apply MLK_ex_falso
      have hor : S ⊢ₘ[insert (q ⟶ ⊥ₘ) L] p ⋎ q := .hyp (by simp [L, K])
      have hnand : S ⊢ₘ[insert (q ⟶ ⊥ₘ) L] ¬((¬p) ⋏ (¬q)) :=
        MLK_modusponens (MLK_iff_imp1 (MLK_axiom_or p q)) hor
      have hnp : S ⊢ₘ[insert (q ⟶ ⊥ₘ) L] ¬p :=
        MLK_not_def.mpr (.hyp (by simp [L]))
      have hnq : S ⊢ₘ[insert (q ⟶ ⊥ₘ) L] ¬q :=
        MLK_not_def.mpr (.hyp (by simp))
      exact MLK_modusponens (MLK_not_def.mp hnand)
        (MLK_and.mpr ⟨hnp, hnq⟩)

-- HOL: `MLK_disj_imp` (`calculus.ml`).
theorem MLK_disj_imp {S H : Set Form} {p q r : Form} :
    (S ⊢ₘ[H] p ⋎ q ⟶ r) ↔
      (S ⊢ₘ[H] p ⟶ r) ∧ (S ⊢ₘ[H] q ⟶ r) := by
  constructor
  · intro h
    exact ⟨MLK_imp_trans (MLK_or_right_th p q) h,
      MLK_imp_trans (MLK_or_left_th p q) h⟩
  · rintro ⟨h₁, h₂⟩
    exact MLK_ante_disj h₁ h₂

-- HOL: `MLK_or_elim` (`calculus.ml`).
theorem MLK_or_elim {S H : Set Form} {p q r : Form}
    (hor : S ⊢ₘ[H] p ⋎ q) (hpr : S ⊢ₘ[H] p ⟶ r)
    (hqr : S ⊢ₘ[H] q ⟶ r) : S ⊢ₘ[H] r :=
  MLK_modusponens (MLK_ante_disj hpr hqr) hor

-- HOL: `MLK_or_transl` (`calculus.ml`).
theorem MLK_or_transl {S H : Set Form} {p q : Form} (r : Form)
    (h : S ⊢ₘ[H] p ⟶ q) : S ⊢ₘ[H] p ⟶ q ⋎ r :=
  MLK_imp_trans h (MLK_or_right_th q r)

-- HOL: `MLK_or_transr` (`calculus.ml`).
theorem MLK_or_transr {S H : Set Form} {p r : Form} (q : Form)
    (h : S ⊢ₘ[H] p ⟶ r) : S ⊢ₘ[H] p ⟶ q ⋎ r :=
  MLK_imp_trans h (MLK_or_left_th q r)

-- HOL: `MLK_frege` (`calculus.ml`).
theorem MLK_frege {S H : Set Form} {p q r : Form}
    (hpqr : S ⊢ₘ[H] p ⟶ q ⟶ r) (hpq : S ⊢ₘ[H] p ⟶ q) :
    S ⊢ₘ[H] p ⟶ r :=
  MLK_modusponens (MLK_modusponens (MLK_axiom_distribimp p q r) hpqr) hpq

-- HOL: `MLK_imp_imp` (`calculus.ml`).
theorem MLK_imp_imp {S H : Set Form} {p q r : Form} :
    (S ⊢ₘ[H] p ⟶ q ⟶ r) ↔ (S ⊢ₘ[H] p ⋏ q ⟶ r) :=
  ⟨MLK_ante_conj, MLK_shunt⟩

-- HOL: `MLK_NC` (`calculus.ml`).
theorem MLK_NC {S H : Set Form} {p : Form} :
    (S ⊢ₘ[H] p ⋏ (¬p)) ↔ (S ⊢ₘ[H] ⊥ₘ) := by
  constructor
  · intro h
    exact MLK_modusponens (MLK_not_def.mp ((MLK_and.mp h).2)) (MLK_and.mp h).1
  · intro h
    exact MLK_and.mpr ⟨MLK_ex_falso h, MLK_ex_falso h⟩

-- HOL: `MLK_NC_ALT` (`calculus.ml`).
theorem MLK_NC_ALT {S H : Set Form} {p q : Form}
    (hp : S ⊢ₘ[H] p) (hnp : S ⊢ₘ[H] ¬p) : S ⊢ₘ[H] q :=
  MLK_ex_falso (MLK_NC.mp (MLK_and.mpr ⟨hp, hnp⟩))

-- HOL: `MLK_nc_th` (`calculus.ml`).
theorem MLK_nc_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] p ⋏ (¬p) ⟶ ⊥ₘ :=
  MLK_ante_conj (MLK_imp_swap (MLK_iff_imp1 (MLK_axiom_not p)))

-- HOL: `MLK_iff_mp` (`calculus.ml`).
theorem MLK_iff_mp {S H : Set Form} {p q : Form}
    (hpq : S ⊢ₘ[H] p ⟷ q) (hp : S ⊢ₘ[H] p) : S ⊢ₘ[H] q :=
  MLK_modusponens (MLK_iff_imp1 hpq) hp

-- HOL: `MLK_iff` (`calculus.ml`).
theorem MLK_iff {S H : Set Form} {p q : Form} (h : S ⊢ₘ[H] p ⟷ q) :
    (S ⊢ₘ[H] p) ↔ (S ⊢ₘ[H] q) :=
  ⟨MLK_iff_mp h, MLK_iff_mp (MLK_iff_sym h)⟩

-- HOL: `MLK_and_comm_th` (`calculus.ml`).
theorem MLK_and_comm_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] p ⋏ q ⟷ q ⋏ p :=
  MLK_imp_antisym
    (MLK_and_intro (MLK_and_right_th p q) (MLK_and_left_th p q))
    (MLK_and_intro (MLK_and_right_th q p) (MLK_and_left_th q p))

-- HOL: `MLK_and_comm` (`calculus.ml`).
theorem MLK_and_comm {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] p ⋏ q) ↔ (S ⊢ₘ[H] q ⋏ p) := MLK_iff (MLK_and_comm_th p q)

-- HOL: `MLK_and_assoc_th` (`calculus.ml`).
theorem MLK_and_assoc_th {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] (p ⋏ q) ⋏ r ⟷ p ⋏ (q ⋏ r) := by
  apply MLK_imp_antisym
  · apply MLK_and_intro
    · exact MLK_imp_trans (MLK_and_left_th (p ⋏ q) r) (MLK_and_left_th p q)
    · apply MLK_and_intro
      · exact MLK_imp_trans (MLK_and_left_th (p ⋏ q) r) (MLK_and_right_th p q)
      · exact MLK_and_right_th (p ⋏ q) r
  · apply MLK_and_intro
    · apply MLK_and_intro
      · exact MLK_and_left_th p (q ⋏ r)
      · exact MLK_imp_trans (MLK_and_right_th p (q ⋏ r)) (MLK_and_left_th q r)
    · exact MLK_imp_trans (MLK_and_right_th p (q ⋏ r)) (MLK_and_right_th q r)

-- HOL: `MLK_and_assoc` (`calculus.ml`).
theorem MLK_and_assoc {S H : Set Form} {p q r : Form} :
    (S ⊢ₘ[H] (p ⋏ q) ⋏ r) ↔ (S ⊢ₘ[H] p ⋏ (q ⋏ r)) :=
  MLK_iff (MLK_and_assoc_th p q r)

-- HOL: `MLK_or_comm` (`calculus.ml`).
theorem MLK_or_comm {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] p ⋎ q) ↔ (S ⊢ₘ[H] q ⋎ p) := by
  constructor <;> intro h
  · exact MLK_or_elim h (MLK_or_left_th q p) (MLK_or_right_th q p)
  · exact MLK_or_elim h (MLK_or_left_th p q) (MLK_or_right_th p q)

-- HOL: `MLK_or_assoc_left_th` (`calculus.ml`).
theorem MLK_or_assoc_left_th {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] p ⋎ (q ⋎ r) ⟶ (p ⋎ q) ⋎ r :=
  MLK_ante_disj (MLK_imp_trans (MLK_or_right_th p q) (MLK_or_right_th (p ⋎ q) r))
    (MLK_ante_disj
      (MLK_imp_trans (MLK_or_left_th p q) (MLK_or_right_th (p ⋎ q) r))
      (MLK_or_left_th (p ⋎ q) r))

-- HOL: `MLK_or_assoc_right_th` (`calculus.ml`).
theorem MLK_or_assoc_right_th {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] (p ⋎ q) ⋎ r ⟶ p ⋎ (q ⋎ r) :=
  MLK_ante_disj
    (MLK_ante_disj (MLK_or_right_th p (q ⋎ r))
      (MLK_imp_trans (MLK_or_right_th q r) (MLK_or_left_th p (q ⋎ r))))
    (MLK_imp_trans (MLK_or_left_th q r) (MLK_or_left_th p (q ⋎ r)))

-- HOL: `MLK_or_assoc_th` (`calculus.ml`).
theorem MLK_or_assoc_th {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] p ⋎ (q ⋎ r) ⟷ (p ⋎ q) ⋎ r :=
  MLK_imp_antisym (MLK_or_assoc_left_th p q r) (MLK_or_assoc_right_th p q r)

-- HOL: `MLK_or_assoc` (`calculus.ml`).
theorem MLK_or_assoc {S H : Set Form} {p q r : Form} :
    (S ⊢ₘ[H] (p ⋎ q) ⋎ r) ↔ (S ⊢ₘ[H] p ⋎ (q ⋎ r)) :=
  ⟨fun h => MLK_modusponens (MLK_or_assoc_right_th p q r) h,
    fun h => MLK_modusponens (MLK_or_assoc_left_th p q r) h⟩

/-! ## Congruence rules -/

-- HOL: `MLK_imp_mono` (`calculus.ml`).
theorem MLK_imp_mono {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p' ⟶ p) (hqq : S ⊢ₘ[H] q ⟶ q') :
    S ⊢ₘ[H] (p ⟶ q) ⟶ (p' ⟶ q') := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K := insert p' (insert (p ⟶ q) H)
  have hp : S ⊢ₘ[K] p := MLK_modusponens
    (MODPROVES_MONO2 hpp (by intro x hx; simp [K, hx])) (.hyp (by simp [K]))
  have hq : S ⊢ₘ[K] q := MLK_modusponens (.hyp (by simp [K])) hp
  exact MLK_modusponens (MODPROVES_MONO2 hqq (by intro x hx; simp [hx])) hq

-- HOL: `MLK_imp_mono_th` (`calculus.ml`).
theorem MLK_imp_mono_th {S H : Set Form} (p p' q q' : Form) :
    S ⊢ₘ[H] ((p' ⟶ p) ⋏ (q ⟶ q')) ⟶ (p ⟶ q) ⟶ (p' ⟶ q') :=
  MLK_ante_conj <| by
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    let K := insert (q ⟶ q') (insert (p' ⟶ p) H)
    have hpp : S ⊢ₘ[K] p' ⟶ p := .hyp (by simp [K])
    have hqq : S ⊢ₘ[K] q ⟶ q' := .hyp (by simp [K])
    exact MLK_imp_mono hpp hqq

-- HOL: `MLK_and_imp` (`calculus.ml`).
theorem MLK_and_imp {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟶ p') (hqq : S ⊢ₘ[H] q ⟶ q') :
    S ⊢ₘ[H] p ⋏ q ⟶ p' ⋏ q' :=
  MLK_and_intro (MLK_imp_trans (MLK_and_left_th p q) hpp)
    (MLK_imp_trans (MLK_and_right_th p q) hqq)

-- HOL: `MLK_and_subst_th` (`calculus.ml`).
theorem MLK_and_subst_th {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟷ p') (hqq : S ⊢ₘ[H] q ⟷ q') :
    S ⊢ₘ[H] p ⋏ q ⟷ p' ⋏ q' :=
  MLK_imp_antisym
    (MLK_and_imp (MLK_iff_imp1 hpp) (MLK_iff_imp1 hqq))
    (MLK_and_imp (MLK_iff_imp2 hpp) (MLK_iff_imp2 hqq))

-- HOL: `MLK_and_subst` (`calculus.ml`).
theorem MLK_and_subst {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟷ p') (hqq : S ⊢ₘ[H] q ⟷ q') :
    (S ⊢ₘ[H] p ⋏ q) ↔ (S ⊢ₘ[H] p' ⋏ q') :=
  MLK_iff (MLK_and_subst_th hpp hqq)

-- HOL: `MLK_imp_subst` (`calculus.ml`).
theorem MLK_imp_subst {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟷ p') (hqq : S ⊢ₘ[H] q ⟷ q') :
    S ⊢ₘ[H] (p ⟶ q) ⟷ (p' ⟶ q') :=
  MLK_imp_antisym
    (MLK_imp_mono (MLK_iff_imp2 hpp) (MLK_iff_imp1 hqq))
    (MLK_imp_mono (MLK_iff_imp1 hpp) (MLK_iff_imp2 hqq))

-- HOL: `MLK_not_subst` (`calculus.ml`).
theorem MLK_not_subst {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] p ⟷ q) : S ⊢ₘ[H] (¬p) ⟷ (¬q) :=
  MLK_imp_antisym (MLK_contrapos (MLK_iff_imp2 h))
    (MLK_contrapos (MLK_iff_imp1 h))

-- HOL: `MLK_not_subst_th` (`calculus.ml`).
theorem MLK_not_subst_th {S H : Set Form} {p q : Form}
    (hpq : S ⊢ₘ[H] p ⟷ q) (hnp : S ⊢ₘ[H] ¬p) : S ⊢ₘ[H] ¬q :=
  MLK_iff_mp (MLK_not_subst hpq) hnp

-- HOL: `MLK_iff_not` (`calculus.ml`).
theorem MLK_iff_not {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] (¬p) ⟷ (¬q)) ↔ (S ⊢ₘ[H] p ⟷ q) := by
  constructor
  · intro h
    exact MLK_iff_trans (MLK_iff_sym (MLK_not_not_th p))
      (MLK_iff_trans (MLK_not_subst h) (MLK_not_not_th q))
  · exact MLK_not_subst

-- HOL: `MLK_or_subst_th` (`calculus.ml`).
theorem MLK_or_subst_th {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟷ p') (hqq : S ⊢ₘ[H] q ⟷ q') :
    S ⊢ₘ[H] p ⋎ q ⟷ p' ⋎ q' := by
  apply MLK_imp_antisym
  · exact MLK_ante_disj
      (MLK_imp_trans (MLK_iff_imp1 hpp) (MLK_or_right_th p' q'))
      (MLK_imp_trans (MLK_iff_imp1 hqq) (MLK_or_left_th p' q'))
  · exact MLK_ante_disj
      (MLK_imp_trans (MLK_iff_imp2 hpp) (MLK_or_right_th p q))
      (MLK_imp_trans (MLK_iff_imp2 hqq) (MLK_or_left_th p q))

-- HOL: `MLK_or_subst_right` (`calculus.ml`).
theorem MLK_or_subst_right {S H : Set Form} (p : Form) {q₁ q₂ : Form}
    (h : S ⊢ₘ[H] q₁ ⟷ q₂) : S ⊢ₘ[H] p ⋎ q₁ ⟷ p ⋎ q₂ :=
  MLK_or_subst_th (MLK_iff_refl_th p) h

-- HOL: `MLK_iff_subst` (`calculus.ml`).
theorem MLK_iff_subst {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟷ p') (hqq : S ⊢ₘ[H] q ⟷ q') :
    S ⊢ₘ[H] (p ⟷ q) ⟷ (p' ⟷ q') :=
  MLK_iff_trans (MLK_iff_def_th p q) <|
    MLK_iff_trans
      (MLK_and_subst_th (MLK_imp_subst hpp hqq) (MLK_imp_subst hqq hpp))
      (MLK_iff_sym (MLK_iff_def_th p' q'))

-- HOL: `MLK_iff_mp_subst` (`calculus.ml`).
theorem MLK_iff_mp_subst {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟷ p') (hqq : S ⊢ₘ[H] q ⟷ q')
    (hpq : S ⊢ₘ[H] p ⟷ q) : S ⊢ₘ[H] p' ⟷ q' :=
  MLK_iff_mp (MLK_iff_subst hpp hqq) hpq

-- HOL: `MLK_imp_mp_subst` (`calculus.ml`).
theorem MLK_imp_mp_subst {S H : Set Form} {p p' q q' : Form}
    (hpp : S ⊢ₘ[H] p ⟷ p') (hqq : S ⊢ₘ[H] q ⟷ q')
    (hpq : S ⊢ₘ[H] p ⟶ q) : S ⊢ₘ[H] p' ⟶ q' :=
  MLK_iff_mp (MLK_imp_subst hpp hqq) hpq

/-! ## Derived modal rules -/

-- HOL: `MLK_box_iff_th` (`calculus.ml`).
theorem MLK_box_iff_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] □(p ⟷ q) ⟶ (□p ⟷ □q) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MLK_imp_antisym
  · apply MLK_modusponens (MLK_axiom_boximp p q)
    exact MLK_box_moduspones
      (MLK_axiom_iffimp1 (S := S) (H := (∅ : Set Form)) p q)
      (.hyp (by simp))
  · apply MLK_modusponens (MLK_axiom_boximp q p)
    exact MLK_box_moduspones
      (MLK_axiom_iffimp2 (S := S) (H := (∅ : Set Form)) p q)
      (.hyp (by simp))

-- HOL: `MLK_box_iff` (`calculus.ml`).
theorem MLK_box_iff {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] □(p ⟷ q)) : S ⊢ₘ[H] □p ⟷ □q :=
  MLK_modusponens (MLK_box_iff_th p q) h

-- HOL: `MLK_box_subst` (`calculus.ml`).
theorem MLK_box_subst {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[(∅ : Set Form)] p ⟷ q) : S ⊢ₘ[H] □p ⟷ □q :=
  MLK_box_iff (MLK_necessitation h)

-- HOL: `MLK_box_and` (`calculus.ml`).
theorem MLK_box_and {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] □(p ⋏ q)) : S ⊢ₘ[H] □p ⋏ □q :=
  MLK_and.mpr
    ⟨MLK_box_moduspones (MLK_and_left_th p q) h,
      MLK_box_moduspones (MLK_and_right_th p q) h⟩

-- HOL: `MLK_box_and_inv` (`calculus.ml`).
theorem MLK_box_and_inv {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] □p ⋏ □q) : S ⊢ₘ[H] □(p ⋏ q) := by
  rcases MLK_and.mp h with ⟨hp, hq⟩
  have hi : S ⊢ₘ[H] □p ⟶ □q ⟶ □(p ⋏ q) :=
    MLK_imp_trans (MLK_imp_box (MLK_and_pair_th p q))
      (MLK_axiom_boximp q (p ⋏ q))
  exact MLK_modusponens (MLK_modusponens hi hp) hq

-- HOL: `MLK_box_and_th` (`calculus.ml`).
theorem MLK_box_and_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] □(p ⋏ q) ⟶ (□p ⋏ □q) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  exact MLK_box_and (.hyp (by simp))

-- HOL: `MLK_box_and_inv_th` (`calculus.ml`).
theorem MLK_box_and_inv_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (□p ⋏ □q) ⟶ □(p ⋏ q) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  exact MLK_box_and_inv (.hyp (by simp))

/-! ## Classical identities -/

-- HOL: `MLK_iff_and_refl` (`calculus.ml`).
theorem MLK_iff_and_refl {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] p ⟷ p ⋏ p :=
  MLK_imp_antisym (MLK_and_intro (MLK_imp_refl_th p) (MLK_imp_refl_th p))
    (MLK_and_left_th p p)

-- HOL: `MLK_and_imp_th1` (`calculus.ml`).
theorem MLK_and_imp_th1 {S H : Set Form} {p q q' : Form}
    (hpq : S ⊢ₘ[H] p ⟶ q) (hpq' : S ⊢ₘ[H] p ⟶ q') :
    S ⊢ₘ[H] p ⟶ q ⋏ q' := MLK_and_intro hpq hpq'

-- HOL: `MLK_and_imp_th` (`calculus.ml`).
theorem MLK_and_imp_th {S H : Set Form} {p q q' : Form}
    (hpq : S ⊢ₘ[H] p ⟷ q) (hpq' : S ⊢ₘ[H] p ⟷ q') :
    S ⊢ₘ[H] p ⟷ q ⋏ q' :=
  MLK_imp_antisym (MLK_and_intro (MLK_iff_imp1 hpq) (MLK_iff_imp1 hpq'))
    (MLK_imp_trans (MLK_and_left_th q q') (MLK_iff_imp2 hpq))

-- HOL: `MLK_and_left_true_th` (`calculus.ml`).
theorem MLK_and_left_true_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] ⊤ₘ ⋏ p ⟷ p :=
  MLK_imp_antisym (MLK_and_right_th ⊤ₘ p)
    (MLK_and_intro (MLK_add_assum p MLK_truth_th) (MLK_imp_refl_th p))

-- HOL: `MLK_and_rigth_true_th` (`calculus.ml`).
theorem MLK_and_rigth_true_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] p ⋏ ⊤ₘ ⟷ p :=
  MLK_imp_antisym (MLK_and_left_th p ⊤ₘ)
    (MLK_and_intro (MLK_imp_refl_th p) (MLK_add_assum p MLK_truth_th))

-- HOL: `MLK_or_rid_th` (`calculus.ml`).
theorem MLK_or_rid_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] p ⋎ ⊥ₘ ⟷ p :=
  MLK_imp_antisym (MLK_ante_disj (MLK_imp_refl_th p) (MLK_ex_falso_th p))
    (MLK_or_right_th p ⊥ₘ)

-- HOL: `MLK_or_lid_th` (`calculus.ml`).
theorem MLK_or_lid_th {S H : Set Form} (p : Form) :
    S ⊢ₘ[H] ⊥ₘ ⋎ p ⟷ p :=
  MLK_imp_antisym (MLK_ante_disj (MLK_ex_falso_th p) (MLK_imp_refl_th p))
    (MLK_or_left_th ⊥ₘ p)

-- HOL: `MLK_contrapos_th` (`calculus.ml`).
theorem MLK_contrapos_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟶ q) ⟶ ((¬q) ⟶ (¬p)) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  exact MLK_contrapos (.hyp (by simp))

-- HOL: `MLK_contrapos_eq_th` (`calculus.ml`).
theorem MLK_contrapos_eq_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟶ q) ⟷ ((¬q) ⟶ (¬p)) := by
  apply MLK_imp_antisym
  · exact MLK_contrapos_th p q
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MLK_modusponens (MLK_axiom_doubleneg q)
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    let K := insert (q ⟶ ⊥ₘ) (insert p (insert ((¬q) ⟶ (¬p)) H))
    have hnq : S ⊢ₘ[K] ¬q := MLK_not_def.mpr (.hyp (by simp [K]))
    have hnp : S ⊢ₘ[K] ¬p := MLK_modusponens (.hyp (by simp [K])) hnq
    exact MLK_modusponens (MLK_not_def.mp hnp) (.hyp (by simp))

-- HOL: `MLK_contrapos_eq` (`calculus.ml`).
theorem MLK_contrapos_eq {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] (¬p) ⟶ (¬q)) ↔ (S ⊢ₘ[H] q ⟶ p) :=
  MLK_iff (MLK_iff_sym (MLK_contrapos_eq_th q p))

-- HOL: `MLK_tnd_th` (`calculus.ml`).
theorem MLK_tnd_th {S H : Set Form} (p : Form) : S ⊢ₘ[H] p ⋎ (¬p) :=
  MLK_bool_cases (MLK_or_right_th p (¬p)) <|
    MLK_imp_trans (MLK_iff_imp2 (MLK_axiom_not p)) (MLK_or_left_th p (¬p))

-- HOL: `MLK_and_eq_or` (`calculus.ml`).
theorem MLK_and_eq_or {S H : Set Form} {p q : Form} :
    (S ⊢ₘ[H] p ⋎ q) ↔ (S ⊢ₘ[H] ¬((¬p) ⋏ (¬q))) :=
  MLK_iff (MLK_axiom_or p q)

-- HOL: `MLK_de_morgan_and_th` (`calculus.ml`).
theorem MLK_de_morgan_and_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (¬(p ⋏ q)) ⟷ ((¬p) ⋎ (¬q)) :=
  MLK_iff_trans
    (MLK_not_subst (MLK_and_subst_th
      (MLK_iff_sym (MLK_not_not_th p)) (MLK_iff_sym (MLK_not_not_th q))))
    (MLK_iff_sym (MLK_axiom_or (¬p) (¬q)))

-- HOL: `MLK_de_morgan_or_th` (`calculus.ml`).
theorem MLK_de_morgan_or_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (¬(p ⋎ q)) ⟷ ((¬p) ⋏ (¬q)) := by
  apply MLK_imp_antisym
  · apply MLK_and_intro
    · exact MLK_contrapos (MLK_or_right_th p q)
    · exact MLK_contrapos (MLK_or_left_th p q)
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MLK_not_def.mpr
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    let K := insert (p ⋎ q) (insert ((¬p) ⋏ (¬q)) H)
    have hn : S ⊢ₘ[K] (¬p) ⋏ (¬q) := .hyp (by simp [K])
    exact MLK_or_elim (.hyp (by simp))
      (MLK_not_def.mp (MLK_and.mp hn).1) (MLK_not_def.mp (MLK_and.mp hn).2)

-- HOL: `MLK_not_true_th` (`calculus.ml`).
theorem MLK_not_true_th {S H : Set Form} : S ⊢ₘ[H] (¬⊤ₘ) ⟷ ⊥ₘ := by
  apply MLK_imp_antisym
  · exact MLK_imp_trans (MLK_iff_imp1 (MLK_axiom_not ⊤ₘ)) <| by
      apply MODPROVES_DEDUCTION_LEMMA.mpr
      exact MLK_modusponens (.hyp (by simp)) MLK_truth_th
  · exact MLK_ex_falso_th (¬⊤ₘ)

-- HOL: `MLK_not_true` (`calculus.ml`).
theorem MLK_not_true {S H : Set Form} :
    (S ⊢ₘ[H] ¬⊤ₘ) ↔ (S ⊢ₘ[H] ⊥ₘ) := MLK_iff MLK_not_true_th

-- HOL: `MLK_proves_iff_pos` (`calculus.ml`).
theorem MLK_proves_iff_pos {S H : Set Form} {p q : Form}
    (hp : S ⊢ₘ[H] p) (hq : S ⊢ₘ[H] q) : S ⊢ₘ[H] p ⟷ q :=
  MLK_imp_antisym (MLK_add_assum p hq) (MLK_add_assum q hp)

-- HOL: `MLK_proves_iff_neg` (`calculus.ml`).
theorem MLK_proves_iff_neg {S H : Set Form} {p q : Form}
    (hp : S ⊢ₘ[H] ¬p) (hq : S ⊢ₘ[H] ¬q) : S ⊢ₘ[H] p ⟷ q :=
  MLK_iff_not.mp (MLK_proves_iff_pos hp hq)

-- HOL: `MLK_imp_introl` (`calculus.ml`).
theorem MLK_imp_introl {S H : Set Form} {p q : Form}
    (h : S ⊢ₘ[H] ¬p) : S ⊢ₘ[H] p ⟶ q :=
  MLK_imp_trans (MLK_not_def.mp h) (MLK_ex_falso_th q)

-- HOL: `MLK_proves_not_or` (`calculus.ml`).
theorem MLK_proves_not_or {S H : Set Form} {p q : Form}
    (hp : S ⊢ₘ[H] ¬p) (hq : S ⊢ₘ[H] ¬q) : S ⊢ₘ[H] ¬(p ⋎ q) :=
  MLK_iff_mp (MLK_iff_sym (MLK_de_morgan_or_th p q)) (MLK_and.mpr ⟨hp, hq⟩)

-- HOL: `MLK_crysippus_th` (`calculus.ml`).
theorem MLK_crysippus_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (¬(p ⟶ q)) ⟷ (p ⋏ (¬q)) := by
  apply MLK_imp_antisym
  · apply MLK_and_intro
    · apply MODPROVES_DEDUCTION_LEMMA.mpr
      apply MLK_modusponens (MLK_axiom_doubleneg p)
      apply MODPROVES_DEDUCTION_LEMMA.mpr
      have hni : S ⊢ₘ[insert (p ⟶ ⊥ₘ) (insert (¬(p ⟶ q)) H)]
          (p ⟶ q) ⟶ ⊥ₘ := MLK_not_def.mp (.hyp (by simp))
      exact MLK_modusponens hni
        (MLK_modusponens (MLK_imp_contr_th p q) (.hyp (by simp)))
    · exact MLK_contrapos (MLK_axiom_addimp q p)
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    apply MLK_not_def.mpr
    apply MODPROVES_DEDUCTION_LEMMA.mpr
    let K := insert (p ⟶ q) (insert (p ⋏ (¬q)) H)
    have hp : S ⊢ₘ[K] p := MLK_modusponens (MLK_and_left_th p (¬q)) (.hyp (by simp [K]))
    have hnq : S ⊢ₘ[K] ¬q := MLK_modusponens (MLK_and_right_th p (¬q)) (.hyp (by simp [K]))
    exact MLK_modusponens (MLK_not_def.mp hnq) (MLK_modusponens (.hyp (by simp)) hp)

-- HOL: `MLK_proves_not_imp` (`calculus.ml`).
theorem MLK_proves_not_imp {S H : Set Form} {p q : Form}
    (hp : S ⊢ₘ[H] p) (hnq : S ⊢ₘ[H] ¬q) : S ⊢ₘ[H] ¬(p ⟶ q) :=
  MLK_iff_mp (MLK_iff_sym (MLK_crysippus_th p q)) (MLK_and.mpr ⟨hp, hnq⟩)

/-! ## Distributivity and remaining propositional schemata -/

-- HOL: `MLK_or_and_distr` (`calculus.ml`).
theorem MLK_or_and_distr {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] (p ⋎ q) ⋏ r) : S ⊢ₘ[H] (p ⋏ r) ⋎ (q ⋏ r) := by
  rcases MLK_and.mp h with ⟨hpq, hr⟩
  exact MLK_or_elim hpq
    (MLK_or_transl (q ⋏ r) (MLK_and_intro (MLK_imp_refl_th p) (MLK_add_assum p hr)))
    (MLK_or_transr (p ⋏ r) (MLK_and_intro (MLK_imp_refl_th q) (MLK_add_assum q hr)))

-- HOL: `MLK_or_and_distr_inv` (`calculus.ml`).
theorem MLK_or_and_distr_inv {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] (p ⋏ r) ⋎ (q ⋏ r)) : S ⊢ₘ[H] (p ⋎ q) ⋏ r :=
  MLK_or_elim h
    (MLK_and_intro
      (MLK_imp_trans (MLK_and_left_th p r) (MLK_or_right_th p q))
      (MLK_and_right_th p r))
    (MLK_and_intro
      (MLK_imp_trans (MLK_and_left_th q r) (MLK_or_left_th p q))
      (MLK_and_right_th q r))

-- HOL: `MLK_or_and_distr_equiv` (`calculus.ml`).
theorem MLK_or_and_distr_equiv {S H : Set Form} {p q r : Form} :
    (S ⊢ₘ[H] (p ⋎ q) ⋏ r) ↔ (S ⊢ₘ[H] (p ⋏ r) ⋎ (q ⋏ r)) :=
  ⟨MLK_or_and_distr, MLK_or_and_distr_inv⟩

-- HOL: `MLK_and_or_distr` (`calculus.ml`).
theorem MLK_and_or_distr {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] (p ⋏ q) ⋎ r) : S ⊢ₘ[H] (p ⋎ r) ⋏ (q ⋎ r) :=
  MLK_or_elim h
    (MLK_and_intro
      (MLK_imp_trans (MLK_and_left_th p q) (MLK_or_right_th p r))
      (MLK_imp_trans (MLK_and_right_th p q) (MLK_or_right_th q r)))
    (MLK_and_intro (MLK_or_left_th p r) (MLK_or_left_th q r))

-- HOL: `MLK_and_or_distr_inv` (`calculus.ml`).
theorem MLK_and_or_distr_inv {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] (p ⋎ r) ⋏ (q ⋎ r)) : S ⊢ₘ[H] (p ⋏ q) ⋎ r := by
  rcases MLK_and.mp h with ⟨hpr, hqr⟩
  exact MLK_or_elim hpr
    (by
      apply MODPROVES_DEDUCTION_LEMMA.mpr
      have hp : S ⊢ₘ[insert p H] p := .hyp (by simp)
      exact MLK_or_elim (MODPROVES_MONO2 hqr (Set.subset_insert _ _))
        (MLK_imp_trans (MLK_modusponens (MLK_and_pair_th p q) hp)
          (MLK_or_right_th (p ⋏ q) r))
        (MLK_or_left_th (p ⋏ q) r))
    (MLK_or_left_th (p ⋏ q) r)

-- HOL: `MLK_and_or_distr_inv_prelim` (`calculus.ml`).
theorem MLK_and_or_distr_inv_prelim {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] (p ⋎ r) ⋏ (q ⋎ r)) : S ⊢ₘ[H] q ⟶ (p ⋏ q) ⋎ r := by
  rcases MLK_and.mp h with ⟨hpr, _⟩
  exact MLK_or_elim hpr
    (MLK_shunt (MLK_or_right_th (p ⋏ q) r))
    (MLK_imp_insert q (MLK_or_left_th (p ⋏ q) r))

-- HOL: `MLK_and_or_distr_equiv` (`calculus.ml`).
theorem MLK_and_or_distr_equiv {S H : Set Form} {p q r : Form} :
    (S ⊢ₘ[H] (p ⋏ q) ⋎ r) ↔ (S ⊢ₘ[H] (p ⋎ r) ⋏ (q ⋎ r)) :=
  ⟨MLK_and_or_distr, MLK_and_or_distr_inv⟩

-- HOL: `MLK_and_or_ldistrib_th` (`calculus.ml`).
theorem MLK_and_or_ldistrib_th {S H : Set Form} (p q r : Form) :
    S ⊢ₘ[H] p ⋏ (q ⋎ r) ⟷ (p ⋏ q) ⋎ (p ⋏ r) := by
  apply MLK_imp_antisym
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    have h := MLK_or_and_distr (S := S) (H := insert (p ⋏ (q ⋎ r)) H)
      (MLK_and.mpr ⟨MLK_modusponens (MLK_and_right_th p (q ⋎ r)) (.hyp (by simp)),
        MLK_modusponens (MLK_and_left_th p (q ⋎ r)) (.hyp (by simp))⟩)
    exact MLK_or_elim h
      (MLK_imp_trans (MLK_and_comm_th q p |> MLK_iff_imp1) (MLK_or_right_th (p ⋏ q) (p ⋏ r)))
      (MLK_imp_trans (MLK_and_comm_th r p |> MLK_iff_imp1) (MLK_or_left_th (p ⋏ q) (p ⋏ r)))
  · exact MLK_ante_disj
      (MLK_and_intro (MLK_and_left_th p q)
        (MLK_imp_trans (MLK_and_right_th p q) (MLK_or_right_th q r)))
      (MLK_and_intro (MLK_and_left_th p r)
        (MLK_imp_trans (MLK_and_right_th p r) (MLK_or_left_th q r)))

-- HOL: `MLK_and_subst_right_th` (`calculus.ml`).
theorem MLK_and_subst_right_th {S H : Set Form} (p q₁ q₂ : Form) :
    S ⊢ₘ[H] (q₁ ⟷ q₂) ⟶ ((p ⋏ q₁) ⟷ (p ⋏ q₂)) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  exact MLK_and_subst_th (MLK_iff_refl_th p) (.hyp (by simp))

-- HOL: `MLK_and_subst_left_th` (`calculus.ml`).
theorem MLK_and_subst_left_th {S H : Set Form} (p₁ p₂ q : Form) :
    S ⊢ₘ[H] (p₁ ⟷ p₂) ⟶ ((p₁ ⋏ q) ⟷ (p₂ ⋏ q)) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  exact MLK_and_subst_th (.hyp (by simp)) (MLK_iff_refl_th q)

-- HOL: `MLK_iff_sym_th` (`calculus.ml`).
theorem MLK_iff_sym_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (p ⟷ q) ⟶ (q ⟷ p) := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  exact MLK_iff_sym (.hyp (by simp))

-- HOL: `MLK_imp_truefalse_th` (`calculus.ml`).
theorem MLK_imp_truefalse_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] (q ⟶ ⊥ₘ) ⟶ p ⟶ (p ⟶ q) ⟶ ⊥ₘ := by
  repeat' apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K := insert (p ⟶ q) (insert p (insert (q ⟶ ⊥ₘ) H))
  have hnq : S ⊢ₘ[K] q ⟶ ⊥ₘ := .hyp (by simp [K])
  have hpq : S ⊢ₘ[K] p ⟶ q := .hyp (by simp [K])
  have hp : S ⊢ₘ[K] p := .hyp (by simp [K])
  exact MLK_modusponens hnq (MLK_modusponens hpq hp)

-- HOL: `MLK_imp_true_rule` (`calculus.ml`).
theorem MLK_imp_true_rule {S H : Set Form} {p q r : Form}
    (hnp : S ⊢ₘ[H] (p ⟶ ⊥ₘ) ⟶ r) (hqr : S ⊢ₘ[H] q ⟶ r) :
    S ⊢ₘ[H] (p ⟶ q) ⟶ r := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  apply MLK_bool_cases (p := p)
  · exact MLK_imp_trans (.hyp (by simp)) (MODPROVES_MONO2 hqr (Set.subset_insert _ _))
  · exact MODPROVES_MONO2 hnp (Set.subset_insert _ _)

-- HOL: `MLK_imp_false_rule` (`calculus.ml`).
theorem MLK_imp_false_rule {S H : Set Form} {p q r : Form}
    (h : S ⊢ₘ[H] (q ⟶ ⊥ₘ) ⟶ p ⟶ r) :
    S ⊢ₘ[H] ((p ⟶ q) ⟶ ⊥ₘ) ⟶ r := by
  apply MODPROVES_DEDUCTION_LEMMA.mpr
  let K₀ := insert ((p ⟶ q) ⟶ ⊥ₘ) H
  apply MLK_bool_cases (p := q)
  · have hnimp : S ⊢ₘ[K₀] (p ⟶ q) ⟶ ⊥ₘ := .hyp (by simp [K₀])
    exact MLK_imp_trans (MLK_imp_trans (MLK_axiom_addimp q p) hnimp)
      (MLK_ex_falso_th r)
  · apply MODPROVES_DEDUCTION_LEMMA.mpr
    let K := insert (q ⟶ ⊥ₘ) K₀
    have hqn : S ⊢ₘ[K] q ⟶ ⊥ₘ := .hyp (by simp [K])
    have hpr : S ⊢ₘ[K] p ⟶ r := MLK_modusponens
      (MODPROVES_MONO2 h (by intro x hx; simp [K, K₀, hx])) hqn
    have hnimp : S ⊢ₘ[K] (p ⟶ q) ⟶ ⊥ₘ := .hyp (by simp [K, K₀])
    exact MLK_bool_cases hpr <| MLK_imp_trans
      (MLK_imp_add_assum p (MLK_ex_falso_th q))
      (MLK_imp_trans hnimp (MLK_ex_falso_th r))

-- HOL: `MLK_iff_true_th` (`calculus.ml`).
theorem MLK_iff_true_th {S H : Set Form} :
    (∀ p, S ⊢ₘ[H] (p ⟷ ⊤ₘ) ⟷ p) ∧
      (∀ p, S ⊢ₘ[H] (⊤ₘ ⟷ p) ⟷ p) := by
  constructor
  · intro p
    apply MLK_imp_antisym
    · apply MODPROVES_DEDUCTION_LEMMA.mpr
      exact MLK_modusponens
        (MLK_modusponens (MLK_axiom_iffimp2 p ⊤ₘ) (.hyp (by simp)))
        MLK_truth_th
    · apply MODPROVES_DEDUCTION_LEMMA.mpr
      exact MLK_imp_antisym (MLK_add_assum p MLK_truth_th)
        (MLK_modusponens (MLK_axiom_addimp p ⊤ₘ) (.hyp (by simp)))
  · intro p
    apply MLK_imp_antisym
    · apply MODPROVES_DEDUCTION_LEMMA.mpr
      exact MLK_modusponens
        (MLK_modusponens (MLK_axiom_iffimp1 ⊤ₘ p) (.hyp (by simp)))
        MLK_truth_th
    · apply MODPROVES_DEDUCTION_LEMMA.mpr
      exact MLK_imp_antisym (MLK_add_assum ⊤ₘ (.hyp (by simp)))
        (MLK_add_assum p MLK_truth_th)

-- HOL: `MLK_imp_clauses` (`calculus.ml`).
theorem MLK_imp_clauses {S H : Set Form} :
    (∀ p, S ⊢ₘ[H] p ⟶ ⊤ₘ) ∧
    (∀ p, (S ⊢ₘ[H] p ⟶ ⊥ₘ) ↔ (S ⊢ₘ[H] ¬p)) ∧
    (∀ p, (S ⊢ₘ[H] ⊤ₘ ⟶ p) ↔ (S ⊢ₘ[H] p)) ∧
    (∀ p, S ⊢ₘ[H] ⊥ₘ ⟶ p) := by
  refine ⟨fun p => MLK_add_assum p MLK_truth_th, ?_, ?_, MLK_ex_falso_th⟩
  · intro p
    exact ⟨MLK_not_def.mpr, MLK_not_def.mp⟩
  · intro p
    constructor
    · intro h; exact MLK_modusponens h MLK_truth_th
    · exact MLK_add_assum ⊤ₘ

-- HOL: `MLK_diam_and_th` (`calculus.ml`).
theorem MLK_diam_and_th {S H : Set Form} (p q : Form) :
    S ⊢ₘ[H] ◇(p ⋏ q) ⟶ (◇p ⋏ ◇q) := by
  change S ⊢ₘ[H] (¬(□(¬(p ⋏ q)))) ⟶ ((¬(□(¬p))) ⋏ (¬(□(¬q))))
  apply MLK_and_intro
  · exact MLK_contrapos <| MLK_imp_box <|
      MLK_contrapos (MLK_and_left_th (S := S) (H := (∅ : Set Form)) p q)
  · exact MLK_contrapos <| MLK_imp_box <|
      MLK_contrapos (MLK_and_right_th (S := S) (H := (∅ : Set Form)) p q)

/-! ## Uniform substitution -/

namespace Form

/-- Uniform substitution of formulas for propositional atoms. -/
-- HOL: `SUBST` (`calculus.ml`).
def subst (f : String → Form) : Form → Form
  | falsum => falsum
  | verum => verum
  | atom a => f a
  | neg p => neg (subst f p)
  | conj p q => conj (subst f p) (subst f q)
  | disj p q => disj (subst f p) (subst f q)
  | imp p q => imp (subst f p) (subst f q)
  | iff p q => iff (subst f p) (subst f q)
  | box p => box (subst f p)

-- HOL: `SUBST`, defining equation for `False` (`calculus.ml`).
@[simp] theorem subst_falsum (f : String → Form) : subst f falsum = falsum := rfl
-- HOL: `SUBST`, defining equation for `True` (`calculus.ml`).
@[simp] theorem subst_verum (f : String → Form) : subst f verum = verum := rfl
-- HOL: `SUBST`, defining equation for `Atom` (`calculus.ml`).
@[simp] theorem subst_atom (f : String → Form) (a : String) :
    subst f (atom a) = f a := rfl
-- HOL: `SUBST`, defining equation for `Not` (`calculus.ml`).
@[simp] theorem subst_neg (f : String → Form) (p : Form) :
    subst f (neg p) = neg (subst f p) := rfl
-- HOL: `SUBST`, defining equation for `&&` (`calculus.ml`).
@[simp] theorem subst_conj (f : String → Form) (p q : Form) :
    subst f (conj p q) = conj (subst f p) (subst f q) := rfl
-- HOL: `SUBST`, defining equation for `||` (`calculus.ml`).
@[simp] theorem subst_disj (f : String → Form) (p q : Form) :
    subst f (disj p q) = disj (subst f p) (subst f q) := rfl
-- HOL: `SUBST`, defining equation for `-->` (`calculus.ml`).
@[simp] theorem subst_imp (f : String → Form) (p q : Form) :
    subst f (imp p q) = imp (subst f p) (subst f q) := rfl
-- HOL: `SUBST`, defining equation for `<->` (`calculus.ml`).
@[simp] theorem subst_iff (f : String → Form) (p q : Form) :
    subst f (iff p q) = iff (subst f p) (subst f q) := rfl
-- HOL: `SUBST`, defining equation for `Box` (`calculus.ml`).
@[simp] theorem subst_box (f : String → Form) (p : Form) :
    subst f (box p) = box (subst f p) := rfl

end Form

/-- Abbreviation for uniform substitution `Form.subst`. -/
-- HOL: `SUBST`; abbreviation for `Form.subst` (`calculus.ml`).
abbrev SUBST := Form.subst

/-- Primitive `K` axioms are closed under uniform substitution. -/
-- HOL: `KAXIOM_SUBST` (`calculus.ml`).
theorem KAXIOM_SUBST (f : String → Form) {p : Form} (h : KAxiom p) :
    KAxiom (p.subst f) := by
  cases h <;> simp <;> constructor

/-- Substitution transports a derivation when the additional axiom set is
closed under that substitution. -/
-- HOL: `SUBST_IMP` (`calculus.ml`).
theorem SUBST_IMP {S H : Set Form} (f : String → Form) {p : Form}
    (hS : ∀ q ∈ S, q.subst f ∈ S) (hp : S ⊢ₘ[H] p) :
    S ⊢ₘ[(Form.subst f) '' H] p.subst f := by
  induction hp with
  | kaxiom h => exact .kaxiom (KAXIOM_SUBST f h)
  | ax h => exact .ax (hS _ h)
  | hyp h => exact .hyp ⟨_, h, rfl⟩
  | modusPonens _ _ ihpq ihp => exact .modusPonens ihpq ihp
  | @necessitation H p hp ih =>
      have ih₀ : S ⊢ₘ[(∅ : Set Form)] p.subst f := by simpa using ih
      exact .necessitation ih₀

/-- Uniform substitution in a derivable equivalence. -/
-- HOL: `SUBSTITUTION_LEMMA` (`calculus.ml`).
theorem SUBSTITUTION_LEMMA {S H : Set Form} (f : String → Form) {p q : Form}
    (hS : ∀ r ∈ S, r.subst f ∈ S) (h : S ⊢ₘ[H] p ⟷ q) :
    S ⊢ₘ[(Form.subst f) '' H] p.subst f ⟷ q.subst f :=
  SUBST_IMP f hS h

/-- Congruence of uniform substitutions whose values are provably equivalent. -/
-- HOL: `SUBST_IFF` (`calculus.ml`).
theorem SUBST_IFF {S H : Set Form} (f g : String → Form) (p : Form)
    (hfg : ∀ a, S ⊢ₘ[(∅ : Set Form)] f a ⟷ g a) :
    S ⊢ₘ[H] p.subst f ⟷ p.subst g := by
  induction p generalizing H with
  | falsum => exact MLK_iff_refl_th ⊥ₘ
  | verum => exact MLK_iff_refl_th ⊤ₘ
  | atom a => exact MODPROVES_MONO2 (hfg a) (Set.empty_subset H)
  | neg p ih => exact MLK_not_subst (ih (H := H))
  | conj p q ihp ihq => exact MLK_and_subst_th (ihp (H := H)) (ihq (H := H))
  | disj p q ihp ihq => exact MLK_or_subst_th (ihp (H := H)) (ihq (H := H))
  | imp p q ihp ihq => exact MLK_imp_subst (ihp (H := H)) (ihq (H := H))
  | iff p q ihp ihq => exact MLK_iff_subst (ihp (H := H)) (ihq (H := H))
  | box p ih => exact MLK_box_subst (ih (H := (∅ : Set Form)))

/-- If falsity is among the hypotheses, every formula is derivable. -/
-- HOL: `MODPROVES_EX_FALSO` (`calculus.ml`).
theorem MODPROVES_EX_FALSO {S H : Set Form} {p : Form} (h : ⊥ₘ ∈ H) :
    S ⊢ₘ[H] p := MLK_ex_falso (.hyp h)

end HOLMS
